spring.application.name=ms-students

# Server
server.port=8082

# Database
spring.datasource.url=jdbc:mysql://db-students:3306/${STUDENTS_DB_NAME}
spring.datasource.username=${STUDENTS_DB_USER}
spring.datasource.password=${STUDENTS_DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Connection pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000

# JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# JWT
jwt.secret=${JWT_SECRET}

# Actuator
management.endpoints.web.base-path=/actuator
management.endpoint.health.probes.enabled=true
