# Production profile

# JPA
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none

# Logging
logging.level.root=WARN
logging.level.com.bookclass.ms_annotations=INFO
logging.level.org.springframework.security=WARN

# Actuator
management.endpoints.web.exposure.include=health
